# Generated by Django 4.2.4 on 2023-09-19 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_buy', models.DateTimeField(auto_now_add=True, verbose_name='время совершения покупки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_order', to='games.game', verbose_name='игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'покупка',
                'verbose_name_plural': 'покупки',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=254, verbose_name='текст')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_comment', to='games.game', verbose_name='игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_comment', to=settings.AUTH_USER_MODEL, verbose_name='кто оставил')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='баланс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='who', to=settings.AUTH_USER_MODEL, verbose_name='чей счет')),
            ],
            options={
                'verbose_name': 'баланс',
                'verbose_name_plural': 'баланс',
                'ordering': ('id',),
            },
        ),
    ]
